name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: lint and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.9.5
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright Browsers
        run: CI=1 PLAYWRIGHT_BROWSERS_PATH=0 npx playwright install chromium

      - name: Run lint
        run: pnpm lint

      - name: Run Playwright tests
        run: CI=1 PLAYWRIGHT_BROWSERS_PATH=0 npx playwright test

      # - name: Upload test results
      #   if: always()
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: playwright-report
      #     path: playwright-report
